# --- !Ups

create table "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "email" varchar not null,
  "password" varchar not null,
  "api_key" varchar not null,
  "created_at" timestamp default current_timestamp,
  "updated_at" timestamp default current_timestamp,
  UNIQUE ("email")
);

# --- !Downs

drop table "users" if exists;
